version: "3.11"

services:
  app1:
    container_name: app1
    build: ./app1

  app2:
    container_name: app2
    build: ./app2

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./logs/:/var/log/nginx/
