name: Branch Protection

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the PR is from 'develop' branch
        if: github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref != 'develop'
        run: |
          echo "Pull requests to main branch are only allowed from 'develop' branch."
          exit 1
